### ISSUE TITLE
Breaks gatsby-plugin-preload-fonts when used as drop in replacement for typeface modules

### ISSUE THREAD

**Issue by quansenB** [fontsource/fontsource#111]
**Describe the bug**
I stumbed across this project today as a recommended drop in replacement for typeface modules when used with gatsby. However after replacing it, it did break usage with gatsby-plugin-preload-fonts

**To Reproduce**
in gatsby-browser:
import "fontsource-rubik";
import "fontsource-roboto-mono";

install gatsby-plugin-preload-fonts and run it following README instructions.

Run webpagetest.org or similar to see 404 when loading fonts (like this: https://www.webpagetest.org/result/201212_DiYE_759e9dc71bfb287e699a16690c9c6c70/)

**Expected behavior**
fontsource works as drop in replacement for typeface

**Screenshots**
![image](https://user-images.githubusercontent.com/47332187/101990156-71b6ae00-3ca5-11eb-96d9-9b9d06e06fba.png)

**Additional context**
Also the font files appear to be bigger than from typeface. They were around 12-17kb consistently now they appear to be above 30kb?

**Comment by ayuhito** [comment]
> in gatsby-browser:
> import "fontsource-rubik";
> import "fontsource-roboto-mono";

This actually only contains weight 400, whilst I can see in the screenshot there is a 404 error for a weight 600 import.

The instructions on Typefaces state for a complete drop-in replacement, you should use:
```js
import "fontsource-rubik/latin.css"
```
which essentially imports all the weights into one CSS file. Something that Fontsource does not follow since that is unnecessary behaviour. This the no-hassle don't change anything approach.

The proper way import method for Fontsource is to specify all the weights as so:
```js 
import "fontsource-rubik/400.css"
import "fontsource-rubik/600.css"
...
```

Perhaps that would resolve the errors with gatsby-plugin-preload-fonts?

> Also the font files appear to be bigger than from typeface. They were around 12-17kb consistently now they appear to be above 30kb?
Our source is directly from Google which was the same for Typefaces. The only explainable difference is that the older version of these fonts were smaller, whilst the new updated ones which Google might push might be bigger.

**Comment by quansenB** [comment]
Hmm, Whether I use 
![image](https://user-images.githubusercontent.com/47332187/102018102-60d07000-3d6b-11eb-9ac2-cdf146a10f00.png)
or
![image](https://user-images.githubusercontent.com/47332187/102018251-8f9b1600-3d6c-11eb-979d-b1156774b2d6.png)
or
![image](https://user-images.githubusercontent.com/47332187/102018364-1d770100-3d6d-11eb-97ae-7ab583386e2c.png)

`{
    "timestamp": 1607878456444,
    "hash": "16989cee614a1170a234477346bf6dcb",
    "assets": {
        "/": {
            "/static/roboto-mono-latin-400-d8ab6e6b16f310580e0570584c0ce6d4.woff2": true,
            "/static/roboto-mono-latin-700-d6ba0e99c52d53b707dbd0d00f0a4d10.woff2": true,
            "/static/rubik-latin-400-ae59d6bdaf6d57315cfd2633349ffd64.woff2": true,
            "/static/rubik-latin-600-8b116f1484cb41affc654e7223b6aee8.woff2": true,
            "/static/roboto-mono-latin-400-normal-add8c9706ad493baf9963330353ea0b1.woff2": true,
            "/static/rubik-latin-400-normal-c60ea76cc216df040231d5351a254c11.woff2": true,
            "/static/rubik-latin-600-normal-c60ea76cc216df040231d5351a254c11.woff2": true,
            "/static/roboto-mono-latin-700-normal-add8c9706ad493baf9963330353ea0b1.woff2": true
        },
        "/dev-404-page/": {
            "/static/roboto-mono-latin-400-d8ab6e6b16f310580e0570584c0ce6d4.woff2": true,
            "/static/roboto-mono-latin-700-d6ba0e99c52d53b707dbd0d00f0a4d10.woff2": true,
            "/static/rubik-latin-400-ae59d6bdaf6d57315cfd2633349ffd64.woff2": true,
            "/static/rubik-latin-600-8b116f1484cb41affc654e7223b6aee8.woff2": true,
            "/static/roboto-mono-latin-400-normal-add8c9706ad493baf9963330353ea0b1.woff2": true,
            "/static/rubik-latin-400-normal-c60ea76cc216df040231d5351a254c11.woff2": true,
            "/static/rubik-latin-600-normal-c60ea76cc216df040231d5351a254c11.woff2": true,
            "/static/roboto-mono-latin-700-normal-add8c9706ad493baf9963330353ea0b1.woff2": true
        }
    }
}`

is produced. I'm not sure why those imports cause it to import twice. Subsequently they aren't uploaded to netlify and thus are producing 404's

**Comment by ayuhito** [comment]
I'm not sure in this case. I don't think I can assist with support relating to gatsby-plugin-preload-fonts since it isn't within Fontsource's scope.

Rather, don't you think it's better if a more framework-agnostic (Gatsby, Next.js and more) solution is found instead in #83? 
The current suggested spec would allow preload fonts to be chosen selectively and decisively since it isn't recommended to preload ALL the fonts within your project (according to best practices), which gatsby-plugin-preload-fonts seems to do.

**Comment by quansenB** [comment]
You seem to be correct. I Investigated a little bit further and came to the conclusion that this is either a gatsby-plugin-preload-fonts issue or related to my setup with postcss and tailwind. Will update this, when I find the bug in case anybody else in the future has a similar problem.

A framework agnostic solution would be absolutely great. Not sure, if I could help there, but I'll spend some thoughts on it.

Thank you for your answers and the development of this project 👍

**Comment by dimitrisnl** [comment]
@quansenB Did you figure this out?

**Comment by quansenB** [comment]
@dimitrisnl I did indeed, but I'm not exactly sure how. My best guess would be related to the plugin order of gatsby-config.js. I have gatsby-plugin-preload-fonts on the second position now, after gatsby-plugin-react-helmet.
