### ISSUE TITLE
Use local font first if present on users system

### ISSUE THREAD

**Issue by viralganatra** [fontsource/fontsource#124]
Hey guys thanks for the awesome work hosting all these fonts! I was wondering would it make sense to defer to a user's local system font if present, i.e. changing the `@font-face` definition to something like:

```
src: ('Open Sans')
```

This way we could save the user having to download the font? What do you guys think? Thanks!

**Comment by ayuhito** [comment]
Using local fonts already exist as a concept and such references are put in a large chunk of Fontsource's packages.

However, new releases from Google seem to remove local references, probably because it sometimes causes inconsistencies per installation. It depends whether the font source itself provides the local font names.

I'll be closing this issue since there isn't anything to change.
