### ISSUE TITLE
monoOne

### ISSUE THREAD

**Issue by ScottGuthart** [fontsource/fontsource#141]
**Font Name**
monoOne

**Link to font source**
https://github.com/zlsa/monoOne

**Link to font license**
https://github.com/zlsa/monoOne/blob/master/LICENSE

**Additional context**
There's also an older version [here](https://github.com/madmalik/mononoki)

![Preview](https://imgur.com/ZnLdWsH.png)

**Comment by ayuhito** [comment]
monoOne and Mononoki look very similar to me. I'd rather add the latter as it is far more up to date and maintained as of now. 

Or are there visual differences that would incentivise me to add both fonts?

**Comment by ScottGuthart** [comment]
I've noticed differences in line spacing in my terminal between the two, but that could just be me.

![monoOne](https://imgur.com/061aNZK.png)
![Mononoki](https://imgur.com/kCfqAfy.png)

**Comment by ayuhito** [comment]
There definitely seems a difference in line spacing there (and perhaps letter spacing too), but everything else looks the same.

I still think I'll go with Mononoki, since I'd rather keep the more updated variant of the font.

Also, Fontsource is intended to be used as a webfont and I assume users should be able to use the CSS line-spacing or letter-spacing selector to make appropriate adjustments.

**Comment by ScottGuthart** [comment]
Ok, cool. Thank you!
