### ISSUE TITLE
Josefin Sans WOFF2s are all the 100 weight variants

### ISSUE THREAD

**Issue by BenjaminNolan** [fontsource/fontsource#142]
**Describe the bug**
All the WOFF2 files in `packages/josefin-sans/files/` are the 100-weight font.

**To Reproduce**
Working example in https://github.com/BenjaminNolan/fontsource-josefin-woff2-bug-report.

**Expected behavior**
WOFF2 files contain the correct font files. :)

**Screenshots**
![josefin-sans-latin-700-normal.woff](https://raw.githubusercontent.com/BenjaminNolan/fontsource-josefin-woff2-bug-report/main/josefin-sans-latin-700-normal-woff.png)
![josefin-sans-latin-700-normal.woff2](https://raw.githubusercontent.com/BenjaminNolan/fontsource-josefin-woff2-bug-report/main/josefin-sans-latin-700-normal-woff2.png)

**Additional context**
Not sure at what point this crept in! Chances are, it prolly happened in other fonts, too.

As a slight tangent to this, there are 15 fonts which fontkit can't cope with when looping the repo code through `**/*-all-400-normal.woff`:

```
✖ [104 / 1030] balthazar: balthazar-all-400-normal.woff...
✖ [158 / 1030] bungee-inline: bungee-inline-all-400-normal.woff...
✖ [202 / 1030] chelsea-market: chelsea-market-all-400-normal.woff...
✖ [251 / 1030] cute-font: cute-font-all-400-normal.woff...
✖ [287 / 1030] east-sea-dokdo: east-sea-dokdo-all-400-normal.woff...
✖ [357 / 1030] galdeano: galdeano-all-400-normal.woff...
✖ [359 / 1030] gamja-flower: gamja-flower-all-400-normal.woff...
✖ [412 / 1030] hi-melody: hi-melody-all-400-normal.woff...
✖ [507 / 1030] krub: krub-all-400-normal.woff...
✖ [620 / 1030] mina: mina-all-400-normal.woff...
✖ [713 / 1030] overlock-sc: overlock-sc-all-400-normal.woff...
✖ [758 / 1030] poor-story: poor-story-all-400-normal.woff...
✖ [812 / 1030] reenie-beanie: reenie-beanie-all-400-normal.woff...
✖ [842 / 1030] ruthie: ruthie-all-400-normal.woff...
✖ [983 / 1030] unica-one: unica-one-all-400-normal.woff...
```

Dunno if that's 'cause they're missing required metadata, or if fontkit is expecting something to be there which is optional.

Balthazar gives
```
TypeError: Cannot read property 'tables' of undefined
    at CmapProcessor.findSubtable (/home/benjamin/jswoff2br/node_modules/fontkit/index.js:3900:39)
```
and Chelsea Market gives
```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 159472. Received 159474
    at boundsError (internal/buffer.js:81:9)
    at Buffer.readInt16BE (internal/buffer.js:501:5)
    at DecodeStream.<computed> [as readInt16BE] (/home/benjamin/jswoff2br/node_modules/restructure/src/DecodeStream.js:38:35)
```
Haven't checked the rest, but I'd guess they're variations on that theme.

**Comment by ayuhito** [comment]
I thought this was an upstream issue at [Google Font Metadata](https://github.com/fontsource/google-font-metadata)... but it turns out that it's even further upstream at Google Fonts itself?

https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;700

You can compare the two weights:

```css
/* latin */
@font-face {
  ...
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/josefinsans/v17/Qw3aZQNVED7rKGKxtqIqX5EUDXx4.woff2) format('woff2');
  ...
}
```

and

```css
/* latin */
@font-face {
  ...
  font-weight: 700;
  src: url(https://fonts.gstatic.com/s/josefinsans/v17/Qw3aZQNVED7rKGKxtqIqX5EUDXx4.woff2) format('woff2');
  ...
}
```

The source files link to the exact same URL (my user agent is with the current latest Chrome update 88). What's even weirder is that this bug seems to have been present for more than [6 months](https://github.com/fontsource/fontsource/tree/master/packages/josefin-sans/files). 

I'll bring this up in the main Google Fonts repository,

As for your latter comments, I'm not too sure either. This repo does try its best to mirror Google's sources and therefore the font files are likely their responsibility.

**Comment by BenjaminNolan** [comment]
Huh, how odd. I guess no-one noticed it as Webkit and Blink must still be prioritising the WOFFs over the WOFF2s. I didn't think to check the upstream CSS, might be possible to script it to see if this affects any other fonts as well. Will look into it when I have a chance!

**Comment by davelab6** [comment]
This is correct; it's a variable font file, so it contains all the weights in 1 file

**Comment by ayuhito** [comment]
Ah, that does remind me why it's like that. We discussed it via this issue [here](https://github.com/NDISCOVER/Exo-2.0/issues/11#issuecomment-728223903). We use the VF user-agent for all WOFF2 fonts. 

Although I'm not sure if the same behaviour is being applied to other fonts with variable variants since this is the first I'm hearing of this bug.

This can be accounted for if we downgrade the user-agent, but we may run into the aforementioned bug with Exo-2 at least. Again,  I'm not sure how other fonts will be affected, but I'm sure there will be changes.

**Comment by ayuhito** [comment]
I'm going to reopen this issue as I think this needs to be addressed. 

Considering Fontsource allows the developer to choose whether they want to import a specific weight or go variable, it seems counterintuitive to serve variable despite the choice. For the previous Exo-2 bug, that is a tradeoff the developer should consider themselves whether they want to go down the variable font route.

What's even more concerning is that each variable font file supports all weights, which could lead to a duplication of downloaded font files if developers choose to import by weight.
To illustrate my point:
```jsx
import "@fontsource/inter/400.css" // downloads "inter-latin-400-normal.woff2" (37KB)
import "@fontsource/inter/500.css" // downloads "inter-latin-500-normal.woff2" (37KB)

import "@fontsource/inter/variable.css" // downloads "inter-latin-variable-wghtOnly-normal.woff2" (37KB)

// The files are all the same!!
```
Both WOFF2 files actually support all weights, yet their different filenames would mean the browser would download both in this situation. The fallback WOFF files which aren't variable are actually smaller in this case.

Thankfully, this only affects fonts that support variable fonts, however, Google is rapidly expanding support for that. The fix for this is also very simple being a user-agent issue upstream with google-font-metadata, but I will need to test this a lot considering this could affect a lot of packages.
