### ISSUE TITLE
Can't import both material-icons and material-icons-outlined

### ISSUE THREAD

**Issue by rockwotj** [fontsource/fontsource#158]
**Is your feature request related to a problem? Please describe.**
I can't use both the outlined and normal material icons in my project.

**Describe the solution you'd like**
I'd like to be able to reference the outlined font family as `'Material Icons Outlined'` like the google fonts version.

**Additional context**
This package is awesome! Thank you for your work here.

**Comment by ayuhito** [comment]
Thoughts on two separated packages for this? That way, it won't require much custom work to implement (since the current code only accommodates one font name per package).

Although, I suppose we can implement the custom logic when working on #152. 

I think the latter might be better for organisation, but the former is still an option.

**Comment by rockwotj** [comment]
I'm totally fine with another package. That makes it a non breaking change too.
