### ISSUE TITLE
Restore TTF/OTF support

### ISSUE THREAD

**Issue by jimustafa** [fontsource/fontsource#184]
**Is your feature request related to a problem? Please describe.**
First off, these packages are great; it would be nice to be able to manage fonts for projects that are not necessarily destined for a browser. While solving the npm publishing problems with #44 makes sense, it could still be worth publishing the TTF/OTF files, when possible. For a possible use case, please see matplotlib/cheatsheets#57.

**Describe the solution you'd like**
Font packages published with OTF/TTF, when possible.

**Describe alternatives you've considered**
To download and install the various fonts needed for a project, using a Makefile has worked, but seems fragile.

**Additional context**
None at this point.

**Comment by ayuhito** [comment]
I don't think adding TTF/OTF support is an option, sadly. It caused a ton of chaos upon implementation and CI success rates tanked.

But, I may have a possible suggestion for you. Fontsource depends on [google-font-metadata](https://github.com/fontsource/google-font-metadata) which parses the Google APIs to produce the relevant download links for each font. I will admit, this library needs a lot of cleanup and I want to repackage it with TSDX, but I've been putting it off since what it needs to do for Fontsource just... works.

You could use the APIv1 data file and pick out the ttf/otf download links as the source, which might be more reliable. I'm not sure if that helps your workflow, but it's the only alternative I can suggest.

**Comment by jimustafa** [comment]
Thanks for the quick reply and a thoughtful response. Will take a look at the package you suggest, and continue any additional discussion there. Thanks again.
