### ISSUE TITLE
Font Request: Polonium

### ISSUE THREAD

**Issue by v1rtl** [fontsource/fontsource#221]
**Font Name**
Polonium

**Link to font source**

Showcase: https://www.behance.net/gallery/116720461/Polonium-Free-Font-%28Latin-and-Cyrillic%29?tracking_source=search_projects_published_date%7Cfree%20font%20cyrillic

Download link: https://drive.google.com/file/d/1DsU01m8wpu7GVWnyVzgZRiGwsjm5yWCQ/view

**Link to font license**

I couldn't find the license file anywhere. Although on the Behance page it says "free for personal and commerical use"

![image](https://user-images.githubusercontent.com/35937217/118724510-5bee7b80-b837-11eb-8933-4ab3cea668b5.png)

**Comment by ayuhito** [comment]
Hey, thanks for the issue.

I can't approve this because of the lack of license. "Free for personal and commerical use" is not sufficient when we need a clause specifying redistribution rights for Fontsource to use. If there is direct permission from the author, I could consider it.

I'll close this issue for now. This could be reopened if the above issues are resolved.
