### ISSUE TITLE
Glitch with Exo 2 uppercase A, B, D, Å, Ä letters since version 4.4.0+, works in 4.3.0

### ISSUE THREAD

**Issue by scmx** [fontsource/fontsource#243]
**Describe the bug**

When using the Exo 2 font with upper case A, B, D, Å or Ä letter then there is a visual glitch where they're not being fully filled in with color when used.

v4.3.0 works as expected
![fontsource-v4-3-0-font-exo-2](https://user-images.githubusercontent.com/603846/120398698-ff14ba00-c33a-11eb-98ea-ccc8f70bd627.png)

v4.4.0 the glitch shows up
![fontsource-v4-4-2-font-exo-2](https://user-images.githubusercontent.com/603846/120398737-0f2c9980-c33b-11eb-8aec-b2f5bd2c8d35.png)

v4.4.2 the glitch remains
![fontsource-v4-4-0-font-exo-2](https://user-images.githubusercontent.com/603846/120398721-089e2200-c33b-11eb-9587-a8e0633a29cd.png)

**To Reproduce**

1. Import Exo 2 `@import '@fontsource/exo-2;`
2. Use Exo 2 `body { font-family: 'Exo 2'; }`
3. Write a big letter A, B, D, Å or Ö on the page
4. See glitch

**Screenshots**

![fontsource-exo-2-glitch](https://user-images.githubusercontent.com/603846/120400084-85ca9680-c33d-11eb-9600-92eaebd8f049.gif)

**Comment by ayuhito** [comment]
This was an issue I was aware of when pushing the 4.4.0 update, but deemed necessary.

A proper explanation of why this is happening can be found at NDISCOVER/Exo-2.0#11, highlighting that this affects a subset of Mac OS users and is an upstream issue.

The reasons why this behaviour suddenly appeared after 4.4.0 is due to the resolution of #142, where it was decided to stop serving variable fonts unless directly specified to do so. This [comment](https://github.com/fontsource/fontsource/issues/142#issuecomment-829358772) in that issue explains why we cannot continue serving variable fonts arbitrarily as it led to duplicated font file downloads and may conflict with some developers who intend to support browsers that do not support the variable font specification.

Steps developers should take:
- Use the variable variant of Exo-2. e.g. `import "@fontsource/exo-2/variable.css"`. The variable font guide for Fontsource can be found [here](https://fontsource.org/docs/variable-fonts). 

Steps Fontsource can take:
- Write up a disclaimer for Exo-2 in the directory that links to this issue and urges for the variable variant to be used. 

- Personally, I believe Fontsource should promote the use of variable fonts and thus update the docs to direct more developers to use that specification in general. 

- Finish #204 which would include a filter for variable fonts, further promoting the use and availability of variable fonts in the Fontsource directory.

I'm not really sure if there is a way for Fontsource to resolve this issue cleanly since it is more of an upstream issue. There are workarounds available as mentioned above, but they come with tradeoffs. I'm open to consider any differing opinions.

**Comment by ayuhito** [comment]
I've added a disclaimer for Exo-2 in #243. I've used an array of font IDs to compare against whether to show the disclaimer because I do know this issue does affect other fonts too.

Please let me know in this issue whether there are any other fonts that are experiencing similar rendering issues and we can update the website accordingly.

**Comment by larzon83** [comment]
@DecliningLotus `Inter` has the same "bug" since v4.4.0

**Comment by ayuhito** [comment]
One additional change Fontsource could make is changing 'index.css' to match 'variable.css' for these affected fonts. Thus the default import wouldn't have any issues and should make things easier for some developers.

Some could argue it to be a breaking change in terms of browser compatibility... except we've been accidentally serving variable fonts since the beginning of this project anyways. Taking that into consideration, it shouldn't really break anyone.
