### ISSUE TITLE
Adding Contributors

### ISSUE THREAD

**Issue by ayuhito** [fontsource/fontsource#258]
Fontsource has grown larger than I have imagined it to ever be and to ensure the longevity and stability of the project, I’m requesting for additional maintainers to help work on this repository. Personally, I’d consider myself to be semi-active and the issues seem to be building up as I have less and less time. Additionally, it would also be nice to have someone peer-review my code and judgements since this is one of my first projects ever and I’m just a student soon to begin my first year of university.

As an overview of the project, everything is built using Typescript, including the core packager. The website is built with Next.js whilst the backend API (still in development #249) uses Fastify NestJS.

There’s actually a lot of undocumented work planned for the frontend website and thus it would be really great to get someone else actively involved with that! I’m no designer, so feel free to change up the UI too. The API, on the other hand, should be fairly low maintenance.

Getting a full code review on the main packager scripts and getting help resolving related issues would also be appreciated.

If you’re interested in helping out and possibly have experience with any of the above frameworks, feel free to drop a message with a way to contact you directly. I’ll be happy to give you a tour of the code and work things out.

**Comment by jwr1** [comment]
Hello @DecliningLotus, I am interested in joining the Fontsource organization. I am already familiar with some of the code contained in this repository. As you know I have contributed several times already, and would like to further add to this repository in the future. I already have knowledge with some of the technologies used, (such as react, node, next, typescript) and am a fast learner for any others I am unfamiliar with. I have a lot of time available and can look in to issues when you may be busy. On that note, if you do decide to accept, I prefer not to give out my email where everyone can see it. What would be a good communication option is slack, which I have used with other teams before. This would be a good option for when the team grows (instead of sending a bunch of emails to different people). I am open to any other communication options you may come up with.

**Comment by ayuhito** [comment]
@jwr12135, I'd be happy to add you. I actually previously wanted to get in touch with you to figure things out from before, but the lack of ways to contact you made me give up.

And yes, I was planning on making a Slack. Feel free to send me a quick email at declininglotus@gmail.com and I'll get back to you with more details (e.g. Slack workspace).

**Comment by snigdha920** [comment]
Hi @ayuhito, I'd be interested in contributing as well! 

I found this package when I was looking at how to add self hosted fonts with NextJS, and it has made my life much easier, so I'd like to contribute and help it's growth! I'm also looking to scale my skills through code reviews and collaborations.

I have experience building enterprise grade systems with NestJS, React, TypeScript, NextJS. 

Here's my:
- Email ID: snigdha920@gmail.com
- LinkedIn: https://www.linkedin.com/in/snigdha-singh-166838184/

Looking forward to hearing from you!

**Comment by ayuhito** [comment]
@snigdha920, glad you're interested. I decided to move over to a Discord so more people can comfortably join without restrictions. Feel free to join us [here](https://discord.gg/UpHW6ZEyde)!

**Comment by ayuhito** [comment]
Closing in favour of #550 as this issue has a lot of outdated information.
