### ISSUE TITLE
Font Request: Noto Fonts

### ISSUE THREAD

**Issue by mike-nl** [fontsource/fontsource#263]
**Font Name**
Noto fonts, e.g. Noto Sans Arabic UI

**Link to font source**
https://github.com/googlefonts/noto-fonts

**Link to font license**
[SIL Open Font License (OFL) v1.1](https://github.com/googlefonts/noto-fonts/blob/main/LICENSE)

**Additional context**
You already have Noto Sans and Noto Serif in a bunch of languages already but I'd be keen for broader support across other languages

**Comment by ayuhito** [comment]
This is a somewhat difficult request to process due to the sheer number of possible fonts and inconsistencies that might be associated with it. 

It’s not something I want to blindly add when the Google Fonts team manages all the Noto fonts too, and I’m not sure when our implementations and theirs (when they finally add it) will conflict. There's a reason they themselves don't consider it production friendly yet.

The [Google Fonts Early Access](https://fonts.google.com/earlyaccess) fonts are an option that I would be more willing to consider, but I'm still wary due to the aforementioned reasons. It's also very laborious requiring tons of manual checking on our end.

**Comment by mike-nl** [comment]
Ah I didn't realise they weren't released yet. Thanks for looking into it :)

**Comment by ayuhito** [comment]
I'll be closing this issue then since I don't think I'm willing to even include the Early Access fonts after reviewing their files. Thanks!

**Comment by schwigri** [comment]
Hi, just wanted to double check on this; I see many Noto fonts on Google Fonts, and the Early Access page linked above shows that many have "graduated." Is it still expected that we cannot get Noto Naskh Arabic or Noto Kufi Arabic from Fontsource?

**Comment by ayuhito** [comment]
@schwigri, you're in huge luck. Just a few hours ago, the Fontsource libraries pulled in an update from Google Fonts. Seems like Google added pretty much ALL the Noto Sans fonts which include the ones you're looking for.

https://github.com/fontsource/fontsource/commit/cbdc12361b65d53948cef77e29bd729d287d65b4

Unfortunately, I am away from my desktop to actually publish those packages on NPM (still haven't fixed our auto-publishing bug oops). I can publish it in around 4-5 days, however.

**Comment by ayuhito** [comment]
All Noto fonts have been published onto NPM.
