### ISSUE TITLE
Saira Condensed / Encode Sans / Encode Sans Condensed all seem to not load

### ISSUE THREAD

**Issue by americool** [fontsource/fontsource#272]
**Describe the bug**
The following fonts don't load and produce a 404 error saira-condensed, encode-sans, encode-sans-condensed (all variants that I've tried)

**To Reproduce**
Try loading them into your project. I'd be curious to know if anyone else is using them successfully. I'm able to use all the other saira and encode sans fonts (semi-expanded, expanded, semi-condensed, etc.) without problems.

**Expected behavior**
(Apologies is this is a bad ticket, but I really can't see why 3 out of 9 fonts  I'm using aren't working

**Screenshots**
![image](https://user-images.githubusercontent.com/16258690/124803249-dd54b700-df26-11eb-8c08-18a3944617d0.png)

**Additional context**

**Comment by ayuhito** [comment]
The packages themselves seem fine with all the necessary files in them.

Are you using Next.js by any chance? #215 might be relevant since your problems look similar, with a solution stated at the bottom of the issue.

If not, could you clarify your build stack?

**Comment by americool** [comment]
Thanks for getting back to me. I'm not using Next.js we're using React/Typescript on top of rails via webpacker. What I honestly find so strange about this is that I'm able to load a number of other fontsource fonts successfully.

**Comment by ayuhito** [comment]
I spun up a quick Next.js website with Saira Condensed, Encode Sans and Encode Sans Condensed on my computer. The fonts all loaded fine and I also tested the specific missing weights that were shown in the screenshot. I wasn't able to reproduce the issue.

I would typically suggest for you to make a minimum reproducible build for me to test it and diagnose the issue, however, I haven't dabbled in Ruby and Webpacker before to actually feel like I could help. It's even more confusing that some Fontsource packages work and some don't.

The general advice I can only give is to try refreshing your build cache and double-checking your imports and Webpack configurations. It might be better for you to make an issue at Webpacker themselves because the files are all there on Fontsource's side, but something is happening with Webpacker for it to not process all the fonts (perhaps some internal limits?).
