### ISSUE TITLE
Missing an all-included CSS file

### ISSUE THREAD

**Issue by leafac** [fontsource/fontsource#289]
**Describe the bug**

I’m migrating from The Typefaces project and I’m having trouble understanding how I should go about it. In Typefaces, there’s the handy CSS including all styles (all weights and their italics), for example, https://unpkg.com/typeface-public-sans@1.1.13/index.css

The closest thing I can find in Fontsource is something like https://unpkg.com/@fontsource/public-sans@4.5.0/latin.css, but that’s missing the italics. And there’s no https://unpkg.com/@fontsource/public-sans@4.5.0/latin-italic.css either.

Ideally there would be a https://unpkg.com/@fontsource/public-sans@4.5.0/all.css, which replaces https://unpkg.com/typeface-public-sans@1.1.13/index.css. But even a combination of https://unpkg.com/@fontsource/public-sans@4.5.0/latin.css and https://unpkg.com/@fontsource/public-sans@4.5.0/latin-italic.css is better than having to import each weight and italics by hand. (Browsers are pretty smart about not downloading fonts that it doesn’t need, so that should be fine.)

Even more ideally, the https://unpkg.com/typeface-public-sans@1.1.13/all.css should be default file in the package, as opposed to the 400 normal. Everything will just work…

**Comment by ayuhito** [comment]
The main reason the all file does not exist anymore is for large fonts such as Noto Sans TC - https://github.com/fontsource/fontsource/blob/main/packages/noto-sans-tc/400.css

Having an all file for something like this would lead to the Noto Sans TC CSS file exceeding 1MB... which really defeats the purpose of splitting up the font into many smaller subsets to reduce final bundle sizes. Furthermore, specificity allows users to minimise the CSS that is included. Sure, browsers may be able to determine whether to download the font or not, but the CSS will always be loaded. No need to include the extra kilobytes, which I'm sure many developers look to optimise. The subset specific file, e.g. `latin.css` does NOT utilise the `unicode-range` selector and thus the all behaviour suits it more. This is a legacy file to ease the transfer from Typefaces, but I don't recommend it unless you have a specific use case to only import a specific subset.

I'm going to favour developer flexibility rather than setting defaults that arguably set bad practices. Typefaces matches closer to how the Google CSS APIv1 performed whilst Fontsource is closer to how Google Fonts CSS APIv2 serves its files. You only need to add a few more lines to your code to support more weights and styles. That isn't difficult nor reducing performance. Most developers only need to import a couple of files from the library and I would rather favour the majority over the minority's convenience who look to import many many weights and styles.

Typefaces never supported any other subsets other than Latin. They simply didn't support any other languages and so their 'all' file is equivalent to our `latin.css` file. 

The only bug I do see is that lack of italics included in `latin.css` since I wanted that file to match how Typefaces served it. We could take a look into fixing that.

**Comment by leafac** [comment]
Thanks for the detailed answer. I was expecting that there would be more to the issue than what met the eyes initially.

I guess including italics on `latin.css` is a good move because it makes the legacy to help transition from Typefaces even more useful.

**Comment by ayuhito** [comment]
Fixed in [v5](https://fontsource.org/docs/getting-started/migrate-v5) 🎉
