### ISSUE TITLE
Variable fonts

### ISSUE THREAD

**Issue by mightyiam** [fontsource/fontsource#30]
Introduction: https://web.dev/variable-fonts/

Not sure whether the service supports this, yet.

We have found that fonts provided in the packages produced by this project are not variable, even when those same fonts are available as variable fonts from Google Fonts.

Here is the upstream issue:
https://github.com/majodev/google-webfonts-helper/issues/97

**Comment by ayuhito** [comment]
We're dependant on that upstream service to add support for pulling data on variable fonts. We're essentially at their mercy otherwise. A pull request that adds support there would be an appropriate step forward.

Alternatively, we can manually incorporate the currently 42 variable fonts that are available from https://fonts.google.com/?vfonly directly, although that is not a long term sustainable option.

Variable fonts is something that I do want to address, but I would want to explore what other options we might have to resolve this.

**Comment by ayuhito** [comment]
Revisiting this issue, I believe we can add support for this by adopting [jonathantneal/google-fonts-complete](https://github.com/jonathantneal/google-fonts-complete) into our build chain. We will need to edit it to pull variable fonts, however, a quick look over the code makes it look doable.

Pros:
- Remove [upstream dependency](https://github.com/majodev/google-webfonts-helper) that may lack updates or stability (their Heroku server being down has failed some of our builds - directly depending on Google Fonts API is more stable).
- More features! Using this would allow for unicode ranges and variable fonts to be pushed to our Google font files automatically and allow us to quickly adopt new things that Google's API adds.

Cons:
- We need to maintain more code.

I find the tradeoff completely acceptable in my eyes and I'll probably start working on a PR that begins the migration in a couple of weeks, but if anyone else has any other thoughts to contribute in the meantime you're welcome to!

**Comment by ayuhito** [comment]
Pending implementation in fontsource/google-font-metadata#4. I've started working on it slowly.

**Comment by ayuhito** [comment]
Finally added upstream support in fontsource/google-font-metadata#14! All that is left are some additional scripts within this repo to download the relevant files and we should have variable font support!

**Comment by ayuhito** [comment]
This has finally been implemented and published to the 3.1.x namespace 🎉 

Note this is still an early-stage implementation and lots of improvements could be made. Feel free to make issues regarding them!

Obligatory mention to @mshuster who made #104. 5+ failed lerna publishes later with no real reason why, the first properly published version is 3.1.5.

**Comment by mshuster** [comment]
It looks like after the lerna failures, you are retagging the release to initiate the npm publish. (since the only difference in the packages seems to be the version number https://github.com/fontsource/fontsource/compare/fontsource-inter@3.1.4...fontsource-inter@3.1.5)

In this case, for next release, if lerna succeeds in push tags to github, but fails to publish to NPM after tagging you can run `lerna publish from-package` https://github.com/lerna/lerna/tree/main/commands/publish#bump-from-package to avoid creating new tags. It will simply attempt to republish to NPM. Unfortunately, I have learned this same thing from experience due to not being correctly authed to private NPM registries.

Thanks again for your work on this! @DecliningLotus

**Comment by ayuhito** [comment]
@mshuster, due to the sheer amount of packages (over one thousand), lerna sometimes hangs halfway through the publish cycle. It might end up publishing 450/1000 packages, then crash due to a couple of unexplainable bugs or even experience memory crashes. 

I hate to admit this, but it's 🙏 and hope all packages publish. If it fails, I wouldn't change anything and republish and somehow it works later. The version bump happens repeatedly because half the packages may be published, and it isn't possible to easily republish the other half accurately.

**Comment by mshuster** [comment]
That sounds super frustrating. If you split the process into `lerna vesion` to push the new version tags, then you can attempt to run `lerna publish from-package` which should try and publish all packages for which versions do not exist in NPM. What's nice about his approach is that if you fail at 450/1000, you can rerun `lerna publish from-package` and it will essentially continue the process by publishing only the packages which don't have the latest version available in NPM (without requiring new tags).

https://github.com/lerna/lerna/tree/main/commands/publish#bump-from-package
> Similar to the from-git keyword except the list of packages to publish is determined by inspecting each package.json and determining if any package version is not present in the registry. Any versions not present in the registry will be published. This is useful when a previous lerna publish failed to publish all packages to the registry.

**Comment by ayuhito** [comment]
@mshuster, thank you for the idea and explanation! I'll have to look into experimenting with this on a smaller test monorepo myself when I find some free time.
