### ISSUE TITLE
material-icons-outlined-400-normal.woff disappeared 

### ISSUE THREAD

**Issue by NZhuravlev** [fontsource/fontsource#315]
**Describe the bug**

Discovered during an update to `@fontsource/material-icons` from 4.2.1 to 4.5.0:

```
Error: Can't resolve '~@fontsource/material-icons/files/material-icons-outlined-400-normal.woff'
```
No mention in the changelog: https://github.com/fontsource/fontsource/blob/main/CHANGELOG.md

**To Reproduce**

1. Set @fontsource/material-icons version to 4.2.1
2. Import `material-icons-outlined-400-normal.woff` somewhere
3. Update to 4.5.0
4. Build

**Expected behavior**
I expect the file to be there

**Comment by ayuhito** [comment]
Material Icons Outlined was moved to a separate package `@fontsource/material-icons-outlined`. 
Reference: #158 and #177.

I will admit, the breaking change was completely overlooked. Apologies. 

A more comprehensive changelog should be introduced. We currently don't include any font-related changes in the main one because there's so much happening weekly with different versions for each font, and much of it is automated. Perhaps a second changelog dedicated to the fonts, e.g. added or updated or changed, would be good but it would require some work to automatically update itself whenever Google pushes its own updates.

**Comment by NZhuravlev** [comment]
Thank you for the quick response!
