### ISSUE TITLE
Font Request: Hauora Sans

### ISSUE THREAD

**Issue by hmaesta** [fontsource/fontsource#336]
## Hauora Sans

Hauora is an open-source sans-serif font family. Hauora is derived from [Manrope](https://manropefont.com/) — designed by [@sharanda](https://github.com/sharanda) — and modified by [WCYS](https://wayneshih.com/) for the Tiaki Hauora Project.

- **Source:** [WCYS-Co/Hauora-Sans](https://github.com/WCYS-Co/Hauora-Sans)
- **License:** [SIL Open Font License 1.1](https://github.com/WCYS-Co/Hauora-Sans/blob/master/OFL.txt)

**Comment by ayuhito** [comment]
Just wanted to update this. I can publish the NPM packages next week because I have no access to my desktop for that period of time.

**Comment by hmaesta** [comment]
@DecliningLotus Thank you for let me know, but don't worry about time. 
I appreciate your hard work on this project and I hope you are on holidays. Take your time! 🙌

**Comment by ayuhito** [comment]
@hmaesta, I ended up writing an entire new publisher replacement for Lerna and it worked! The previous Lerna setup limited it to my desktop only due to the onslaught of bugs caused by it, but this one finally works in the GitHub Actions without an issue!

You should be able to find the package on NPM now.
