### ISSUE TITLE
Add Material Icons fonts

### ISSUE THREAD

**Issue by petermikitsh** [fontsource/fontsource#36]
**Is your feature request related to a problem? Please describe.**

When querying fonts.google.com, font families "Material Icons" and "Material Icons Outlined" don't appear, but Google does host them:

https://fonts.googleapis.com/icon?family=Material+Icons
https://fonts.googleapis.com/icon?family=Material+Icons+Outlined

https://fonts.googleapis.com/css2?family=Material+Icons
https://fonts.googleapis.com/css2?family=Material+Icons+Outlined

**Describe the solution you'd like**

Packages `fontsource-material-icons` and `fontsource-material-icons-outlined`

**Describe alternatives you've considered**

The icons do exist elsewhere: https://github.com/material-icons/material-icons

**Comment by ayuhito** [comment]
@petermikitsh, I'm hesitant to approve this for the sole reason that icon fonts are considered to be worse than the newer SVG frameworks that let you select and import only the icon you need.

Why do you think this would be better than something such as [react-icons](https://github.com/react-icons/react-icons) or even downloading and linking the individual SVG icon you need [here](https://material.io/resources/icons/)? I would think that something like that is far more suitable for icons rather than integrating it into Fontsource which aims to provide locally hosted benefits for typefaces specifically.

**Comment by petermikitsh** [comment]
My use case is a complex web application with UIs built in a wide set of technologies: React, Vue, Angular, Server-side rails applications, Server-side Java (JSPs), etc. Shipping a framework-level solution would only cover a small subsection of my entire application. I agree, there are some optimizations you can't make with icon fonts-- e.g., no code splitting for only the icons you need, for example. Consequently, bundle sizes are slightly larger, but that's an acceptable tradeoff in my use case because the distribution method of a font file simplifies the problem of adopting standard iconography throughout the application.

If I was in a greenfield project situation, I would follow your approach (use exclusively React, React SVGs for code splitting, etc).

**Comment by ayuhito** [comment]
That sounds fair, especially considering there isn't any difficulty importing the files in with the generic packager scripts we have. I'll look into addressing that within a couple of days.

**Comment by ayuhito** [comment]
I decided to make the two variants into different subsets rather than publishing separate packages. e.g. `import fontsource-material-icons/base.css` or `import fontsource-material-icons/outlined.css`.

Whilst I like the potential of having 5 subsets, such as two-tone, utilising [material-icons/material-icons-font](https://github.com/material-icons/material-icons-font), unfortunately, the repository seems a little concerning with it boldly stating it to be WIP, having a lack of license and lack of changelog.

Perhaps in the future, a manual update can be pushed here to expand the fontsource mirror.
