### ISSUE TITLE
Cooper Hewitt

### ISSUE THREAD

**Issue by johnridesabike** [fontsource/fontsource#67]
**Cooper Hewitt**

**Link to font source**
This was on Typefaces, but the font files seem to be missing now: https://github.com/KyleAMathews/typefaces/tree/master/packages/cooper-hewitt

You can get the font files from an older version: https://unpkg.com/browse/typeface-cooper-hewitt@0.0.44/

**Link to font license**
SIL OFL
https://github.com/KyleAMathews/typefaces/blob/master/packages/cooper-hewitt/SIL%20Open%20Font%20License.txt

**Additional context**
Until this is on Fontsource, then the [instructions from the Typefaces README are broken](https://github.com/KyleAMathews/typefaces/blob/master/packages/cooper-hewitt/README.md):

> To start using Fontsource, replace in your package.json any instances of "typeface-cooper-hewitt" with "fontsource-cooper-hewitt".

**Comment by johnridesabike** [comment]
Thanks for the quick response! I have one question: Is there a reason the available weights are different from the typefaces package?

Weights in typeface-cooper-hewitt: 100, 200, 300, 400, 500, 600, 700, 800

Weights in fontsource-cooper-hewitt: 100, 200, 300, 500, 600, 700, 900

Fontsource has removed 400, and 800, and added 900. Is that an error, or were they incorrect in the typefaces package?

**Comment by ayuhito** [comment]
Oh, I must've made a mistake there. I do recall seeing the 400 files in the packaging process but must've overlooked something for it to not be published... 

800 and 900 are the same. Considering Cooper Hewitt is extremely old and was using an old naming scheme for the weights, it was a rough guess whether it was 800 or 900.

I'll look into pushing fixes tomorrow since it is late for me. I'll change 900 to 800 for the sake of consistency for our migrating Typefaces users.

**Comment by johnridesabike** [comment]
Thanks again! It looks great. 👍
