### ISSUE TITLE
fontsource-open-sans-condensed is missing a default export file `index.css`

### ISSUE THREAD

**Issue by vjwilson** [fontsource/fontsource#68]
**Describe the bug**
Switching from the `typefaces` package to this one.

There is no default `index.css` file in the `open-sans-condensed` package, even though its package.json specifies an entry point of `"main": "index.css"`.

**To Reproduce**

1. Add `"fontsource-open-sans": "^3.0.9"`, and `"fontsource-open-sans-condensed": "^3.0.9",` to `package.json`
2. Run `yarn install`
3. Add `import 'fontsource-open-sans';` and `import 'fontsource-open-sans-condensed';` to React's `index.js`
4. Open-Sans loads correctly, but Open-Sans-Condensed fails to load with the error **_Module not found: Can't resolve 'fontsource-open-sans-condensed'_**

**Expected behavior**
That there would be a default export for the open-sans-condensed package, like there is for the open-sans package, so that folks could keep their import statements consistent.

If this is intentional, or due to a technical limitation, please let me know. If not, I would appreciate a fixed version at some point in the future.

**Screenshots**
![Screen Shot 2020-10-09 at 9 54 37 AM](https://user-images.githubusercontent.com/715729/95591607-8496d300-0a15-11eb-8c03-d4e0d6906ae6.png)

**Additional context**
Not that I can think of.

**Comment by ayuhito** [comment]
For seamless migration from Typefaces, it is recommended you use `import fontsource-open-sans-condensed/latin.css` which should make your stated issue 'fixed', as stated in the note on top of the Typefaces [readme](https://www.npmjs.com/package/typeface-open-sans-condensed). You are able to specify specific weights if you read more of the documentation [here](https://github.com/fontsource/fontsource/tree/master/packages/open-sans-condensed#additional-options).

## Issue

That said, this still is a bug for regular users. As shown in the Fontsource [readme](https://www.npmjs.com/package/fontsource-open-sans-condensed), Open Sans Condensed only supports weights 300 and 700.

Fontsource makes the gross assumption that weight 400 exists everywhere and thus it will generate the default index.css on the occurrence of that specific weight. Since Open Sans Condensed does not support 400, index.css is never generated. I assume this bug affects a very small subset of existing fonts in the repository considering Google _usually_ ensures fonts to have a regular 400 typeface.

Ignoring the default import and using `import fontsource-open-sans-condensed/300.css` or `import fontsource-open-sans-condensed/700.css` is the current workaround.

## Resolution

I'm unsure what the best approach is to the problem? In the instance we have weights 300 and 500. Would we assume index.css to be generated for 300 or 500? I'd want some outside opinion with justification on this before properly addressing this issue.

On top of that, documentation is hardcoded to state 400 is always the default import, so we would need to additionally develop something to account for that.
