### ISSUE TITLE
Add individual links to search directory for each font

### ISSUE THREAD

**Issue by jwr1** [fontsource/fontsource#79]
Adding links to the search directory would be useful for easy acsess for those wanting to see a preview or information about the font. We can take advantage of the search directories url hash which has the search directory url, then a **#** symbol, then the id of the font. Fontsource search directory automatically sets the url when you click on a font.

For example, on Roboto's [README.md](https://github.com/fontsource/fontsource/blob/master/packages/roboto/README.md) we could have:

> # Fontsource Roboto
> 
> [![npm version](https://badge.fury.io/js/fontsource-roboto.svg)](https://www.npmjs.com/package/fontsource-roboto) [![Generic badge](https://img.shields.io/badge/fontsource-passing-brightgreen)](https://github.com/fontsource/fontsource) [![Monthly downloads](https://badgen.net/npm/dm/fontsource-roboto)](https://github.com/fontsource/fontsource) [![Total downloads](https://badgen.net/npm/dt/fontsource-roboto)](https://github.com/fontsource/fontsource) [![GitHub stars](https://img.shields.io/github/stars/DecliningLotus/fontsource.svg?style=social&label=Star)](https://github.com/fontsource/fontsource/stargazers)
> 
> The CSS and web font files to easily self-host the “Roboto” font. Please visit the main [Fontsource monorepo](https://github.com/fontsource/fontsource) to view more details on this package. **To preview the font, open it with the [fontsource search directory](https://fontsource.github.io/search-directory/#roboto).**

**Comment by ayuhito** [comment]
I've got a lot planned for the search-directory in terms of organisation and personal pickiness. 

Moving the growing README to it's own documentation section within the directory and changing what information is shown to the end user to be more intuitive are two key things I want to address.

Hence I'm treating the current directory as WIP and not fully committing to promoting it till I'm happy with it, since I feel the README offers a bit more currently.

Once I get time to focus on that, I'll make a bunch of issues and also implement most of the changes for me to be comfortable to publicise and promote it more.
