### ISSUE TITLE
Inter: Italics missing

### ISSUE THREAD

**Issue by mikerockett** [fontsource/fontsource#90]
**Describe the bug**

The Inter font does not have the italic styles. The `<weight>.css` and `<weight>-normal.css` files are identical.

**Expected behavior**

There should be an italic variant. Would also be nice if you could support the variable font. 🎉

**Comment by ayuhito** [comment]
Our repository mirrors Google Fonts exactly and thus we don't have an italic variation of this font since Google themselves don't export it: https://fonts.google.com/specimen/Inter

Inter does, however, have a SLNT axis as a variable font. This will be addressed on completion of #30. I've just struggled to find time to speed through implementing that in this repo, but all upstream updates at [fontsource/google-font-metadata](https://github.com/fontsource/google-font-metadata) to produce variable font data have been completed.

I'll be closing this issue now since there isn't much else we can do for your request.

**Comment by mikerockett** [comment]
Thanks for the detailed explanation @DecliningLotus – didn't realise that Google wasn't exporting italics. Pulling the font from the designer’s website for now. 🙂
