### ISSUE TITLE
Jetbrains Mono - 400, 500, 700 specific stylesheets give an error

### ISSUE THREAD

**Issue by austriker27** [fontsource/fontsource#91]
**Describe the bug**
I'm not able to load the 400, 500, and 700 weights specifically via their respective stylesheets in JavaScript. I've used this same technique to load specific font weights from Inter (open source) and Sora (google font) via fontsource. 

**To Reproduce**

1. install `fontsource-jetbrains-mono` (I'm using `yarn` if that matters)

2. Add stylesheets to JavaScript:
```
import 'fontsource-jetbrains-mono/400.css'
import 'fontsource-jetbrains-mono/500.css'
import 'fontsource-jetbrains-mono/700.css'
```
3. Console error:
`Module not found: Error: Can't resolve 'fontsource-jetbrains-mono/400.css' `
`Module not found: Error: Can't resolve 'fontsource-jetbrains-mono/500.css' `
`Module not found: Error: Can't resolve 'fontsource-jetbrains-mono/700.css' `

**Expected behavior**
I expected those weights to load based on the Fontsource page [here](https://fontsource.github.io/search-directory/#jetbrains-mono) that says they are available. 

If I do a generic import (`import 'fontsource-jetbrains-mono'`) there is no error.

**Comment by ayuhito** [comment]
Hey @austriker27, thanks for checking in.

#92 should address _why_ this issue exists and that it is on the agenda to be fixed. If you refer to the package readme on [NPM](https://www.npmjs.com/package/fontsource-jetbrains-mono) or [GitHub](https://github.com/fontsource/fontsource/tree/master/packages/jetbrains-mono#readme), it has a filler subset called 'all'.

The current method to import this would be:
```js
import 'fontsource-jetbrains-mono/all-400.css'
import 'fontsource-jetbrains-mono/all-500-normal.css'
import 'fontsource-jetbrains-mono/all-700-italic.css'
```

I'll be closing this for now since #92 will address how to improve the issue you're seeing.
