### ISSUE TITLE
Archivo font not functional in React: Chrome & Firefox

### ISSUE THREAD

**Issue by RyRy79261** [fontsource/fontsource#95]
**Describe the bug**
Following the docs for `fontsource-archivo` attempting to load the index.css, 

Firefox encounters a sanitizer error

```downloadable font: rejected by sanitizer (font-family: "Archivo" style:normal weight:400 stretch:100 src index:0) source: http://localhost:3000/files/archivo-latin-400-normal.woff2```

Chrome fails to load the fonts:
![image](https://user-images.githubusercontent.com/10461622/100207060-cd481400-2f0f-11eb-8ba8-9022f7df77e0.png)

**To Reproduce**

1. add `import "fontsource-archivo/index.css"` in your entry file
2. Add `'Archivo'` as the first entry in your font stack
3. Open in either Chrome or firefox

**Expected behavior**
Font loads as expected

**Screenshots**

**Additional context**
Typescript, React, Jss

**Comment by ayuhito** [comment]
This error is most commonly linked with a misconfigured Webpack setup. 

Try the solution in #84 and see if that works for you?

**Comment by RyRy79261** [comment]
@DecliningLotus I'm using RollUp to package the component where this is being implemented

**Comment by ayuhito** [comment]
I genuinely have no clue whether Rollup even supports the way Fontsource imports fonts since Webpack is the only tested bundler.

Maybe there is a way to make it work, but I've never used Rollup before or experimented.

[This](https://stackoverflow.com/questions/51970359/resolve-woff-imports-with-rollup/54416164) might be helpful.

**Comment by ayuhito** [comment]
Issue closed due to no discussion taking place over a couple of months.
