### ISSUE TITLE
Supporting non-open source fonts

### ISSUE THREAD

**Issue by dougajmcdonald** [fontsource/fontsource#96]
**Is your feature request related to a problem? Please describe.**
I have a use case where a client has provided proprietary fonts, but I'd like to use one single approach to self-hosting fonts.

**Describe the solution you'd like**
Is there a way I can leverage the functions offered through font-source but perhaps a parameter or mode to point it to a local folder rather than the standard import? or similar?

**Comment by ayuhito** [comment]
I'm not sure if I understand the purpose of this.

There aren't necessarily any extra functions that Fontsource offers that I can imagine makes this useful. 

I'd be more inclined to recommend you handle this manually instead.

**Comment by dougajmcdonald** [comment]
Sorry if I didn't describe it particularly well.

What I'm imagining is being able to use something like fontsource to load a font from google fonts, but also load fonts from a local folder in src. The use case is when you need to load a non OS font you've purchased.

Whilst as you say you could load it in manually it would be nice to have a universal way to load a font from whatever source location you wish. Otherwise I'm left having to say, load one theme using one method and another in a separate way which feels a bit clunky.

**Comment by ayuhito** [comment]
I can't imagine adding something like this, because Fontsource simply just creates import paths to pre-generated CSS files. 

`import "../your-font-folder/font-name.css"`
Fontsource is essentially this but resolving to the node_modules folder to get the CSS file. We can't pre-generate CSS files for random fonts that don't go through the build process within this repository. It just isn't possible to accommodate your request unless it joins our repository.

Once again, I'd say you should do something manually and import it like how I wrote earlier alongside the Fontsource options. 

I'll be closing this since I genuinely can't see a way to accommodate what you are asking.
